sudo: false
language: node_js
node_js:
  - '11'
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
before_install:
  - yarn upgrade
install:
  - yarn
script:
  - yarn test
  - yarn coveralls
